//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfStarter.UI.Localisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfStarter.UI.Localisation.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В работе приложения произошла критическая ошибка.
        /// </summary>
        public static string CriticalError {
            get {
                return ResourceManager.GetString("CriticalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закройте окно и перезапустите приложение.
        /// </summary>
        public static string CriticalErrorHelp {
            get {
                return ResourceManager.GetString("CriticalErrorHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите строку подключения.
        /// </summary>
        public static string DataBase {
            get {
                return ResourceManager.GetString("DataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключиться.
        /// </summary>
        public static string DbConnect {
            get {
                return ResourceManager.GetString("DbConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка подключения к базе данных. .
        /// </summary>
        public static string DBError {
            get {
                return ResourceManager.GetString("DBError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сброс настроек.
        /// </summary>
        public static string DropSettings {
            get {
                return ResourceManager.GetString("DropSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбран пустой файл.
        /// </summary>
        public static string ErrorFileEmpty {
            get {
                return ResourceManager.GetString("ErrorFileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберете файл .csv.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cохранить в формате.
        /// </summary>
        public static string FileSave {
            get {
                return ResourceManager.GetString("FileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Столбец.
        /// </summary>
        public static string FilterColumn1 {
            get {
                return ResourceManager.GetString("FilterColumn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действие.
        /// </summary>
        public static string FilterColumn2 {
            get {
                return ResourceManager.GetString("FilterColumn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры.
        /// </summary>
        public static string FilterColumn3 {
            get {
                return ResourceManager.GetString("FilterColumn3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все данные.
        /// </summary>
        public static string FilterDataAll {
            get {
                return ResourceManager.GetString("FilterDataAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле содержит .
        /// </summary>
        public static string FilterDataContains {
            get {
                return ResourceManager.GetString("FilterDataContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать все.
        /// </summary>
        public static string FilterOptionSelectAll {
            get {
                return ResourceManager.GetString("FilterOptionSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string FilterRow1 {
            get {
                return ResourceManager.GetString("FilterRow1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string FilterRow2 {
            get {
                return ResourceManager.GetString("FilterRow2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string FilterRow3 {
            get {
                return ResourceManager.GetString("FilterRow3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество.
        /// </summary>
        public static string FilterRow4 {
            get {
                return ResourceManager.GetString("FilterRow4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город.
        /// </summary>
        public static string FilterRow5 {
            get {
                return ResourceManager.GetString("FilterRow5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страна.
        /// </summary>
        public static string FilterRow6 {
            get {
                return ResourceManager.GetString("FilterRow6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки выборки данных.
        /// </summary>
        public static string FilterTitle {
            get {
                return ResourceManager.GetString("FilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запуск операции.
        /// </summary>
        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузчик из .CSV в базу данных Microsoft SQL.
        /// </summary>
        public static string HeaderTitle {
            get {
                return ResourceManager.GetString("HeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберете файл для загрузки.
        /// </summary>
        public static string Help1 {
            get {
                return ResourceManager.GetString("Help1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщите администратору об ошибке.
        /// </summary>
        public static string Help2 {
            get {
                return ResourceManager.GetString("Help2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл анализируется на ошибки. Ожидайте.
        /// </summary>
        public static string Help3 {
            get {
                return ResourceManager.GetString("Help3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберете требуемую операцию.
        /// </summary>
        public static string Help4 {
            get {
                return ResourceManager.GetString("Help4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите &quot;Запуск&quot; .
        /// </summary>
        public static string Help5 {
            get {
                return ResourceManager.GetString("Help5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидайте завершения.
        /// </summary>
        public static string Help6 {
            get {
                return ResourceManager.GetString("Help6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить таблицу как файл Excel.
        /// </summary>
        public static string OpConvToXLSX {
            get {
                return ResourceManager.GetString("OpConvToXLSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить таблицу как XML.
        /// </summary>
        public static string OpConvToXML {
            get {
                return ResourceManager.GetString("OpConvToXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать таблицу и загрузить файл.
        /// </summary>
        public static string OpCSVtoSQLCreate {
            get {
                return ResourceManager.GetString("OpCSVtoSQLCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить файл в cуществующую таблицу.
        /// </summary>
        public static string OpCSVtoSQLExist {
            get {
                return ResourceManager.GetString("OpCSVtoSQLExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Табличные данные.
        /// </summary>
        public static string OpenFileFormat {
            get {
                return ResourceManager.GetString("OpenFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string OpError {
            get {
                return ResourceManager.GetString("OpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка загрузки из CSV файла.
        /// </summary>
        public static string OpLoadFromFileError {
            get {
                return ResourceManager.GetString("OpLoadFromFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Записи добавлены частично. Ошибок чтения: .
        /// </summary>
        public static string OpReadyWithErrors {
            get {
                return ResourceManager.GetString("OpReadyWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все записи успешно добавлены.
        /// </summary>
        public static string OpRecordsAdded {
            get {
                return ResourceManager.GetString("OpRecordsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверные настройки программы.
        /// </summary>
        public static string OpWrongSettings {
            get {
                return ResourceManager.GetString("OpWrongSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберать другой файл.
        /// </summary>
        public static string SelectAnotherFile {
            get {
                return ResourceManager.GetString("SelectAnotherFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый файл.
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвертер и заполнитель БД из файлов .СSV.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
